server:
  port: 8081

spring:
  application.name: movie-info-service

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientId: movieinfo
      clientSecret: 1234

    resource:
      userInfoUri: http://localhost:8080/user